<script setup></script>

<template>
  <div class="bg-base-200 h-screen w-screen">
    <div class="h-screen w-screen bg-white">
      <div
        class="absolute inset-x-0 bottom-0 flex h-20 w-screen flex-row items-center justify-evenly border-t-2 border-indigo-200"
      >
        <div class="h-14 w-14 bg-blue-300"><div>1</div></div>
        <div class="h-14 w-14 bg-blue-300"><div>2</div></div>
        <div class="h-14 w-14 bg-blue-300"><div>3</div></div>
      </div>
    </div>
  </div>
</template>
